SELECT a.PRODUCT_ID,a.PRODUCT_NAME, sum(b.amount*a.price) TOTAL_SALES from FOOD_PRODUCT a join FOOD_ORDER b on a.PRODUCT_ID=b.PRODUCT_ID
where b.PRODUCE_DATE like '%2022-05%' 
group by b.PRODUCT_ID
order by TOTAL_SALES desc ,a.PRODUCT_ID