-- 코드를 작성해주세요
select YEAR(DIFFERENTIATION_DATE) YEAR,
(select max(SIZE_OF_COLONY) from ECOLI_DATA where year(DIFFERENTIATION_DATE) = YEAR ) - SIZE_OF_COLONY YEAR_DEV,
ID from ECOLI_DATA 
order by YEAR,YEAR_DEV